# GRPO Algorithm Configuration
defaults: "grpo_infinisst.yaml"

grpo:
  reduce_baseline_rewards: false
  normalize_rewards: false

policy:
  generation:
    top_p: 0.9
    top_k: 100
    vllm_kwargs:
      enable_prompt_embeds: false
  
  optimizer:
    name: "torch.optim.AdamW"
    kwargs:
      lr: 5e-7
      weight_decay: 0.01
      betas: [0.9, 0.999]
      eps: 1e-8
      # when using Dtensor, we need to set foreach
      # and fused to False
      foreach: False
      fused: False

  scheduler:
    - name: "torch.optim.lr_scheduler.ConstantLR"
      kwargs:
        factor: 1.0
        total_iters: 10000000000
    - milestones: []

env:
  infinisst:
    cfg:
      scoring_model_type: "google/metricx-24-hybrid-large-v2p6-bfloat16"
      scoring_model_path: "/ckpts/llm/metricx-24-hybrid-large-v2p6-bfloat16"
      scoring_tokenizer_path: "/ckpts/llm/mt5-xl"
      qe: false
      alpha: 1.0
      beta: 0.0
      max_latency: 10.0
      normalize: true
  
checkpointing:
  checkpoint_dir: "/ckpts/infinisst-rl/grpo-metricx-laal-alpha1.0-beta0.0-envnorm1-grponorm0-run2"

logger:
  wandb:
    project: "infinisst-rl"
    name: "grpo-metricx-laal-alpha1.0-beta0.0-envnorm1-grponorm0-run2"