# GRPO Algorithm Configuration
defaults: "grpo_infinisst_interactive.yaml"

grpo:
  num_prompts_per_step: 2
  max_rollout_turns: 60 # Maximum turns allowed per rollout
  val_at_start: false
  max_val_samples: 32
  val_batch_size: 32

policy:
  model_name: "/ckpts/infinisst/yodas_5kh_v2_m12_stage2_7b_1node/checkpoints/step=2000-last.ckpt.hf"
  train_global_batch_size: 4

  generation:
    vllm_kwargs:
      enable_prompt_embeds: false
 
env:
  infinisst:
    cfg:
      num_gpus: 1
      
logger:
  wandb_enabled: false

cluster:
  gpus_per_node: 1
  num_nodes: 1
