# GRPO Algorithm Configuration
defaults: "grpo_infinisst_nr.yaml"

policy:
  generation:
    vllm_kwargs:
      enable_prompt_embeds: false
  
  optimizer:
    name: "torch.optim.AdamW"
    kwargs:
      lr: 1e-6
      weight_decay: 0.01
      betas: [0.9, 0.999]
      eps: 1e-8
      # when using Dtensor, we need to set foreach
      # and fused to False
      foreach: False
      fused: False

checkpointing:
  checkpoint_dir: "/ckpts/infinisst-rl/grpo-lcme-nr-vllm-lr1e-6-run1"

logger:
  wandb:
    project: "infinisst-rl"
    name: "grpo-lcme-nr-vllm-lr1e-6-run1"