# GRPO Algorithm Configuration
defaults: "grpo_infinisst_interactive.yaml"

grpo:
  num_prompts_per_step: 8
  max_rollout_turns: 60 # Maximum turns allowed per rollout
  val_at_start: false
  max_val_samples: 128
  val_batch_size: 128
  normalize_rewards: false
  reduce_baseline_rewards: false

policy:
  model_name: "/ckpts/infinisst/yodas_5kh_v2_m12_stage2_7b_1node/checkpoints/step=2000-last.ckpt.hf"
  train_global_batch_size: 128

  generation:
    top_p: 0.999
    top_k: 10000
    max_new_tokens: 40
    vllm_kwargs:
      enable_prompt_embeds: false

data:
  train_data_file: "/data/asr/yodas/npy/parakeet-tdt-0.6b-v2_robust60-1120_langid_zh_blaser2.0-qe3.0_metricx-qe4.0_simalign/en000/manifest.parquet"
  val_data_file: "/data/asr/yodas/npy/parakeet-tdt-0.6b-v2_robust60-1120_langid_zh_blaser2.0-qe3.0_metricx-qe4.0_simalign/en_dev/manifest.parquet"
  train_data_shuffle: true
  val_data_shuffle: false
  seed: 42
  src_lang: "en"
  tgt_lang: "zh"
 
env:
  infinisst:
    cfg:
      scoring_model_type: "google/metricx-24-hybrid-large-v2p6-bfloat16"
      scoring_model_path: "/ckpts/llm/metricx-24-hybrid-large-v2p6-bfloat16"
      scoring_tokenizer_path: "/ckpts/llm/mt5-xl"
      # scoring_model_type: "Unbabel/XCOMET-XL"
      # scoring_model_path: "/ckpts/llm/xcomet-xl"
      qe: false
      alpha: 1.0
      beta: 0.0
      max_latency: 10.0
      normalize: true
      num_gpus: 1
      
logger:
  wandb_enabled: false

cluster:
  gpus_per_node: 1
  num_nodes: 1
