# GRPO Algorithm Configuration
defaults: "grpo_infinisst_nr_vllm_bsz64.yaml"

env:
  infinisst:
    cfg:
      scoring_model_type: "google/metricx-24-hybrid-large-v2p6-bfloat16"
      scoring_model_path: "/ckpts/llm/metricx-24-hybrid-large-v2p6-bfloat16"
      scoring_tokenizer_path: "/ckpts/llm/mt5-xl"
      qe: false

checkpointing:
  checkpoint_dir: "results/grpo-infinisst-lcme-nr-vllm-bsz64-metricx"

logger:
  wandb:
    project: "grpo-dev"
    name: "infinisst-lcme-nr-vllm-bsz64-metricx"